export const GENERAL_TEXT_LANGUAGE_ID = 'muxus-text';

const FILE_NAME_LANGUAGES: Readonly<Record<string, string>> = {
  '.bash_aliases': 'shell',
  '.bash_login': 'shell',
  '.bash_logout': 'shell',
  '.bash_profile': 'shell',
  '.bashrc': 'shell',
  '.editorconfig': 'ini',
  '.env': 'shell',
  '.eslintrc': 'json',
  '.gitattributes': 'ini',
  '.gitconfig': 'ini',
  '.jscsrc': 'json',
  '.jshintrc': 'json',
  '.babelrc': 'json',
  '.npmrc': 'ini',
  '.profile': 'shell',
  '.rhistory': 'r',
  '.rprofile': 'r',
  '.zlogin': 'shell',
  '.zlogout': 'shell',
  '.zprofile': 'shell',
  '.zshenv': 'shell',
  '.zshrc': 'shell',
  containerfile: 'dockerfile',
  dockerfile: 'dockerfile',
  gemfile: 'ruby',
  jakefile: 'javascript',
  kubeconfig: 'yaml',
  rakefile: 'ruby',
  'ssh_config': 'ini',
  'sshd_config': 'ini',
};

/** Monaco's complete built-in Monarch catalog, kept here so language selection
 * is available before the large, lazy editor bundle has loaded. Long compound
 * extensions must appear in the same map; matching below always chooses the
 * longest suffix. */
const EXTENSION_LANGUAGES: Readonly<Record<string, string>> = {
  '.abap': 'abap',
  '.aes': 'aes',
  '.ascx': 'xml',
  '.asp': 'html',
  '.aspx': 'html',
  '.azcli': 'azcli',
  '.bash': 'shell',
  '.bat': 'bat',
  '.bicep': 'bicep',
  '.bowerrc': 'json',
  '.c': 'c',
  '.cake': 'csharp',
  '.cc': 'cpp',
  '.cjs': 'javascript',
  '.clj': 'clojure',
  '.cljc': 'clojure',
  '.cljs': 'clojure',
  '.cls': 'apex',
  '.cmd': 'bat',
  '.coffee': 'coffeescript',
  '.conf': 'ini',
  '.config': 'xml',
  '.cpp': 'cpp',
  '.cpy': 'python',
  '.cs': 'csharp',
  '.cshtml': 'razor',
  '.csproj': 'xml',
  '.csp': 'csp',
  '.css': 'css',
  '.csx': 'csharp',
  '.ctp': 'php',
  '.cts': 'typescript',
  '.cxx': 'cpp',
  '.cyp': 'cypher',
  '.cypher': 'cypher',
  '.dart': 'dart',
  '.dats': 'postiats',
  '.dax': 'msdax',
  '.dockerfile': 'dockerfile',
  '.desktop': 'ini',
  '.dtd': 'xml',
  '.ecl': 'ecl',
  '.edn': 'clojure',
  '.es6': 'javascript',
  '.ex': 'elixir',
  '.exs': 'elixir',
  '.flow': 'flow9',
  '.fs': 'fsharp',
  '.fsi': 'fsharp',
  '.fsscript': 'fsharp',
  '.fsx': 'fsharp',
  '.ftl': 'freemarker2',
  '.ftlh': 'freemarker2',
  '.ftlx': 'freemarker2',
  '.gemspec': 'ruby',
  '.gitconfig': 'ini',
  '.go': 'go',
  '.gql': 'graphql',
  '.graphql': 'graphql',
  '.gyp': 'python',
  '.gypi': 'python',
  '.h': 'c',
  '.handlebars': 'handlebars',
  '.har': 'json',
  '.hats': 'postiats',
  '.hbs': 'handlebars',
  '.hcl': 'hcl',
  '.hh': 'cpp',
  '.hpp': 'cpp',
  '.htm': 'html',
  '.html': 'html',
  '.html.liquid': 'liquid',
  '.hxx': 'cpp',
  '.i3': 'm3',
  '.iecplc': 'st',
  '.iecst': 'st',
  '.ig': 'm3',
  '.ini': 'ini',
  '.jade': 'pug',
  '.jav': 'java',
  '.java': 'java',
  '.js': 'javascript',
  '.jscsrc': 'json',
  '.jshtm': 'html',
  '.jshintrc': 'json',
  '.json': 'json',
  '.jsonc': 'json',
  '.jsp': 'html',
  '.jsx': 'javascript',
  '.jl': 'julia',
  '.kt': 'kotlin',
  '.kts': 'kotlin',
  '.lc3lib': 'st',
  '.less': 'less',
  '.lex': 'lexon',
  '.ligo': 'pascaligo',
  '.liquid': 'liquid',
  '.lua': 'lua',
  '.m': 'objective-c',
  '.m3': 'm3',
  '.markdown': 'markdown',
  '.md': 'markdown',
  '.mdoc': 'html',
  '.mdown': 'markdown',
  '.mdtext': 'markdown',
  '.mdtxt': 'markdown',
  '.mdwn': 'markdown',
  '.mdx': 'mdx',
  '.mg': 'm3',
  '.mjs': 'javascript',
  '.mkd': 'markdown',
  '.mkdn': 'markdown',
  '.ml': 'fsharp',
  '.mligo': 'cameligo',
  '.mli': 'fsharp',
  '.msdax': 'msdax',
  '.mts': 'typescript',
  '.opf': 'xml',
  '.p': 'pascal',
  '.pas': 'pascal',
  '.php': 'php',
  '.php4': 'php',
  '.php5': 'php',
  '.phtml': 'php',
  '.pl': 'perl',
  '.pla': 'pla',
  '.pm': 'perl',
  '.pp': 'ruby',
  '.pq': 'powerquery',
  '.pqm': 'powerquery',
  '.properties': 'ini',
  '.props': 'xml',
  '.proto': 'proto',
  '.ps1': 'powershell',
  '.psd1': 'powershell',
  '.psm1': 'powershell',
  '.pug': 'pug',
  '.py': 'python',
  '.pyw': 'python',
  '.qs': 'qsharp',
  '.r': 'r',
  '.rb': 'ruby',
  '.rbx': 'ruby',
  '.redis': 'redis',
  '.rhistory': 'r',
  '.rjs': 'ruby',
  '.rkt': 'scheme',
  '.rlib': 'rust',
  '.rmd': 'r',
  '.rprofile': 'r',
  '.rpy': 'python',
  '.rq': 'sparql',
  '.rs': 'rust',
  '.rst': 'restructuredtext',
  '.rt': 'r',
  '.s': 'mips',
  '.sats': 'postiats',
  '.sb': 'sb',
  '.sbt': 'scala',
  '.sc': 'scala',
  '.scala': 'scala',
  '.sch': 'scheme',
  '.scm': 'scheme',
  '.scss': 'scss',
  '.sh': 'shell',
  '.shtml': 'html',
  '.sol': 'sol',
  '.sql': 'sql',
  '.ss': 'scheme',
  '.st': 'st',
  '.sv': 'systemverilog',
  '.svg': 'xml',
  '.svgz': 'xml',
  '.svh': 'systemverilog',
  '.swift': 'swift',
  '.targets': 'xml',
  '.tcl': 'tcl',
  '.tcdut': 'st',
  '.tcgvl': 'st',
  '.tcio': 'st',
  '.tcpou': 'st',
  '.tf': 'hcl',
  '.tfvars': 'hcl',
  '.timer': 'ini',
  '.toml': 'ini',
  '.ts': 'typescript',
  '.tsp': 'typespec',
  '.tsx': 'typescript',
  '.twig': 'twig',
  '.v': 'verilog',
  '.vb': 'vb',
  '.vh': 'verilog',
  '.wgsl': 'wgsl',
  '.wxi': 'xml',
  '.wxl': 'xml',
  '.wxs': 'xml',
  '.xaml': 'xml',
  '.xhtml': 'html',
  '.xml': 'xml',
  '.xsd': 'xml',
  '.xsl': 'xml',
  '.xslt': 'xml',
  '.yaml': 'yaml',
  '.yml': 'yaml',
};

const EXTENSIONS_BY_LENGTH = Object.keys(EXTENSION_LANGUAGES).sort(
  (left, right) => right.length - left.length,
);

function languageFromFirstLine(content: string): string | undefined {
  const firstLine = content.slice(0, content.indexOf('\n') === -1 ? content.length : content.indexOf('\n'));
  if (/^#!.*\b(?:node|deno|bun)\b/i.test(firstLine)) return 'javascript';
  if (/^#!.*\bpython[0-9.-]*\b/i.test(firstLine)) return 'python';
  if (/^#!.*\b(?:ruby|jruby)\b/i.test(firstLine)) return 'ruby';
  if (/^#!.*\bperl\b/i.test(firstLine)) return 'perl';
  if (/^#!.*\b(?:pwsh|powershell)\b/i.test(firstLine)) return 'powershell';
  if (/^#!.*\b(?:ba|da|k|z)?sh\b/i.test(firstLine)) return 'shell';
  if (/^\s*(?:<\?xml\b|<svg\b|<!doctype\s+svg\b)/i.test(firstLine)) return 'xml';
  return undefined;
}

/** Resolve a file to one of Monaco's built-in language ids. */
export function languageForPath(path: string, content = ''): string {
  const lowerPath = path.toLowerCase().replaceAll('\\', '/');
  if (
    /(?:^|\/)\.kube\/config$/.test(lowerPath) ||
    /(?:^|\/)kubeconfig(?:-[^/]*)?$/.test(lowerPath) ||
    /^\/etc\/kubernetes\/[^/]+\.conf$/.test(lowerPath)
  ) {
    return 'yaml';
  }
  if (/(?:^|\/)\.aws\/(?:config|credentials)$/.test(lowerPath)) return 'ini';

  const name = path.slice(path.lastIndexOf('/') + 1);
  const lowerName = name.toLowerCase();
  if (lowerName.startsWith('.env.')) return 'shell';
  const exact = FILE_NAME_LANGUAGES[lowerName];
  if (exact) return exact;

  for (const extension of EXTENSIONS_BY_LENGTH) {
    if (lowerName.endsWith(extension)) return EXTENSION_LANGUAGES[extension]!;
  }

  return languageFromFirstLine(content) ?? GENERAL_TEXT_LANGUAGE_ID;
}
